[build-system]
requires = ["setuptools>=64", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "ghe_transcribe"
dynamic = ["version"]
dependencies = [
    "torch",
    "torchaudio",
    "typer",
    "av",
    "faster-whisper",
    "pyannote.audio",
    "ipywidgets",
]
scripts = {transcribe = "ghe_transcribe.core:app"}

[tool.setuptools_scm]
local_scheme = "node-and-date"
write_to = "src/ghe_transcribe/_version.py"