name: Python application

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/ghe_transcribe/**'
      - '!src/ghe_transcribe/_version.py'
      - 'tests/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/ghe_transcribe/**'
      - '!src/ghe_transcribe/_version.py'
      - 'tests/**'

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
        pip install -e .
    - name: Test with pytest
      env:
        HUGGINGFACE_TOKEN: ${{secrets.HUGGINGFACE_TOKEN}}
      run: |
        pytest tests/test_core.py